theme: jekyll-theme-primer
title: Lambda Live Debugger
author: Marko (ServerlessLife)
email: marko@serverlesslife.com
keywords: aws, lambda, debugger, serverless, aws-lambda, javascript, typescript, dev-tools, lambda-debugger, aws-cdk, serverless-framework, sls, aws-sam, sam, terraform, local-debugging, cloud-development
description: Tool for remote debugging AWS Lambda functions
url: https://www.lldebugger.com
image:
  path: https://www.lldebugger.com/logo.png
  width: 289
  height: 266
  alt: Lambda Live Debugger
logo: https://www.lldebugger.com/logo.png
twitter:
  username: ServerlessL
og_image: https://www.lldebugger.com/logo.png
social:
  links:
    - 'https://twitter.com/ServerlessL'
    - 'https://www.linkedin.com/in/marko-serverlesslife/'
favicon: ./favicon.ico
avatar: https://www.lldebugger.com/logo.png
