AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Role for GitHub Actions

Resources:
  GithubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GithubOIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: "sts.amazonaws.com"
              StringLike:
                token.actions.githubusercontent.com:sub: "repo:ServerlessLife/lambda-live-debugger:*"
      Policies:
        - PolicyName: CloudFormationDeploy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeChangeSet
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:GetTemplate
                  - cloudformation:ListStackResources
                Resource:
                  - Fn::Sub: arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*

        - PolicyName: CDKBootstrapPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iam:AttachRolePolicy
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:DeleteRolePolicy
                  - iam:DetachRolePolicy
                  - iam:GetRole
                  - iam:GetRolePolicy
                  - iam:PutRolePolicy
                  - iam:TagRole
                  - iam:PassRole
                Resource:
                  - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/cdk-hnb659fds-cfn-exec-role-*
                  - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/cdk-hnb659fds-file-publishing-role-*
                  - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/cdk-hnb659fds-image-publishing-role-*
                  - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/cdk-hnb659fds-lookup-role-*
                  - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/cdk-hnb659fds-deploy-role-*
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:DeleteBucketPolicy
                  - s3:GetEncryptionConfiguration
                  - s3:GetBucketLocation
                  - s3:GetBucketPolicy
                  - s3:PutBucketPolicy
                  - s3:PutBucketVersioning
                  - s3:PutEncryptionConfiguration
                  - s3:PutLifecycleConfiguration
                  - s3:PutBucketPublicAccessBlock
                Resource:
                  - Fn::Sub: arn:aws:s3:::cdk-hnb659fds-assets-*
              - Effect: Allow
                Action:
                  - s3:DeleteObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                Resource:
                  - arn:aws:s3:::cdk*
              - Effect: Allow
                Action:
                  - ssm:DeleteParameter
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                  - ssm:PutParameter
                Resource:
                  - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cdk-bootstrap/hnb659fds/version
              - Effect: Allow
                Action:
                  - ecr:CreateRepository
                  - ecr:DeleteRepository
                  - ecr:DescribeRepositories
                  - ecr:PutLifecyclePolicy
                  - ecr:SetRepositoryPolicy
                Resource:
                  - Fn::Sub: arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/cdk-hnb659fds-container-assets-*

        - PolicyName: SLSandSAMDeployPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - lambda:*
                Resource: "*"

        - PolicyName: IoTPermissionToRunDebugger
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iot:DescribeEndpoint
                  - iot:Connect
                  - iot:Subscribe
                  - iot:Publish
                  - iot:Receive
                Resource:
                  - "*"

        - PolicyName: RunLLDebugger
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:GetFunction
                  - lambda:UpdateFunctionConfiguration
                  - lambda:InvokeFunction
                  - lambda:ListLayerVersions
                  - lambda:GetLayerVersion
                  - lambda:PublishLayerVersion
                  - lambda:DeleteLayerVersion
                  - lambda:ListLayers
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:PutRolePolicy
                  - iam:GetRolePolicy
                  - iam:DeleteRolePolicy
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStackResource
                Resource: "*"

Outputs:
  GitHubActionsRoleArn:
    Description: "ARN of the GitHub Actions IAM Role"
    Value: !GetAtt GitHubActionsRole.Arn
