name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type'
        required: true
        default: 'alpha'
        type: choice
        options:
          - alpha
          - beta
          - stable

permissions:
  id-token: write
  contents: write

env:
  node_version: 22

jobs:
  build:
    uses: ./.github/workflows/common-build.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/common-test.yml
    secrets: inherit
    needs: build
    with:
      mode: build
      testMonorepo: false

  publish:
    needs: test
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    concurrency:
      group: publish
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Semantic Release
        run: |
          npm whoami
          if [ "${{ github.event.inputs.release-type }}" != "stable" ]; then
            npx semantic-release --tag ${{ github.event.inputs.release-type }}
          else
            npx semantic-release
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
